### PR TITLE
v2.0.0 - New UI and major bug fixes

### PR DESCRIPTION
**Pull request by hcshires**
**UI Changelog:**
- Updated login and register pages to start up on launch and be contained in the main window
- Gray color scheme
- Larger Tkinter window
- Decreased popups to a minimum, otherwise all "pages" are rendered in the same window
- Updated about and settings pages
- Converted "List, view, and edit airlines" to one window and simpler design
- Connection test and Update checks now produce message boxes instead of a line printed to the log
- Added "sign out" feature
- Added "remember me" feature
- Main.pyw includes a class with all of the Tkinter widgets for efficiency
- Shrunk file structure for efficiency

**Bug fixes:**
- Fixed pre-file bug of unable to select an aircraft
- Fixed pirep file bug where the flight time is calculated incorrectly
- Fixed FSUIPC txt logging bug where the save path is required to be in the AppData installation location
- Fixed settings not saving after tweaking them (they can now be saved without restarting the application)
- Fixed top windows not closing even after the root closes
- Additional API and UI fixes

**End result:**
Annotation 2020-08-14 220634
Annotation 2020-08-14 220646

### CODE REVIEW

**Comment by slimit75** [comment]
Looks great! Ill take a look at it shortly

**Comment by hcshires** [comment]
Awesome thanks!

**Comment by hcshires** [comment]
There might be an additional issue with the flight time I discovered after I was finished, where phpVMS interprets the flight time as all hours and no minutes. Let me know if you look into that as well.

**Comment by slimit75** [comment]
Currently trying to log in, seem to be having an issue when it throws an error when the details are correct. Will update later

**Comment by slimit75** [comment]
Just did a test flight with it (X-Plane 11.50rc1, Zibo 3.43) and it didnt log anything. Will be looking into this.

**Comment by slimit75** [comment]
Found the issue and just pushed a commit that fixes it. I will try another flight later today to see if that fixed it.

**Comment by slimit75** [comment]
> There might be an additional issue with the flight time I discovered after I was finished, where phpVMS interprets the flight time as all hours and no minutes. Let me know if you look into that as well.

Is the image below what you were referring to? I didnt know KPHX to KABQ could take so long myself
image

**Comment by hcshires** [comment]
Haha yes that exactly

**Comment by slimit75** [comment]
Alright, ill look into it. Doing another test flight right now, position is good, but gs, alt, and heading might not be synced. Can you check this when I submit the pirep, if phpVMS lets you? The map has the correct heading but I wanna be sure that its not xACARS
image

**Comment by hcshires** [comment]
No that is a phpVMS sorry!

**Comment by slimit75** [comment]
Alright, thanks. Ill probably merge this pull request in a couple of days

**Pull request merged**
